
// Objective-C API for talking to the following Go packages
//
//	github.com/smartcontractkit/chainlink
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Chainlink_FRAMEWORK_H__
#define __Chainlink_FRAMEWORK_H__

#include "Chainlink.objc.h"
#include "universe.objc.h"

#endif
