// Objective-C API for talking to github.com/smartcontractkit/chainlink Go package.
//   gobind -lang=objc github.com/smartcontractkit/chainlink
//
// File is generated by gobind. Do not edit.

#ifndef __Chainlink_H__
#define __Chainlink_H__

@import Foundation;
#include "Universe.objc.h"


// skipped function NewProductionClient with unsupported parameter or return types


// skipped function Run with unsupported parameter or return types


FOUNDATION_EXPORT void ChainlinkStart(NSString* pwdfile, NSString* apicredentials);

#endif
